### ISSUE TITLE
Pinning traits>=6.1.0 in CI

### ISSUE THREAD

**Issue by MBueschelberger** [force-h2020/force-bdss-plugin-nevergrad#26]
During unittests of the current master branch, it appears that the plugin relies on the `traits>=6.1.0` since `Union` is not available in the earlier versions of the `traits.api`.

The operation mentioned in the title of this issue might solve this problem, if any incompatible `traits`-version was previously installed during the setup of the `force_bdss`. 

Suggestion for [this](https://github.com/force-h2020/force-bdss-plugin-nevergrad/blob/886dc301b7065d1d3b686c04e22d7520a3f9fbd5/ci/__main__.py#L9) line:

```
ADDITIONAL_CORE_DEPS = [
    "traits>=6.1.0"
]
```

Current error message:

```
======================================================================
ERROR: force_nevergrad.mco.tests.test_ng_mco (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: force_nevergrad.mco.tests.test_ng_mco
Traceback (most recent call last):
  File "C:\Users\FhG_Gast\.edm\envs\force-py36\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\FhG_Gast\.edm\envs\force-py36\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "C:\Users\FhG_Gast\Desktop\force-bdss-plugin-nevergrad\force_nevergrad\mco\tests\test_ng_mco.py", line 23, in <module>
    from force_nevergrad.nevergrad_plugin import NevergradPlugin
  File "C:\Users\FhG_Gast\Desktop\force-bdss-plugin-nevergrad\force_nevergrad\nevergrad_plugin.py", line 6, in <module>  
    from force_nevergrad.mco.ng_mco_factory import NevergradMCOFactory
  File "C:\Users\FhG_Gast\Desktop\force-bdss-plugin-nevergrad\force_nevergrad\mco\ng_mco_factory.py", line 13, in <module>
    from .ng_mco_model import NevergradMCOModel
  File "C:\Users\FhG_Gast\Desktop\force-bdss-plugin-nevergrad\force_nevergrad\mco\ng_mco_model.py", line 9, in <module>  
    from force_nevergrad.engine.nevergrad_optimizers import ALGORITHMS_KEYS
  File "C:\Users\FhG_Gast\Desktop\force-bdss-plugin-nevergrad\force_nevergrad\engine\nevergrad_optimizers.py", line 11, in <module>
    from traits.api import (
ImportError: cannot import name 'Union'
```

**Comment by flongford** [comment]
@MBueschelberger - please see #27, which should close this issue
